informacao = input('Digite qualquer coisa: ')
print('O tipo primitivo é:', type(informacao))
print('Tem espaços?', informacao.isspace())
print('É um número?', informacao.isalnum())
print('É alfabético?', informacao.isalpha())
print('É alfanumérico?', informacao.isalpha())
print('Está em maiúsculo?', informacao.isupper())
print('Está em minúsculo?', informacao.islower())
print('Está capitalizada?', informacao.istitle())
print('É um dígito?', informacao.isdigit())
print('é decimal?', informacao.isdecimal())
